<?php

namespace Modules\Inventario\Models;

use Illuminate\Database\Eloquent\Model;

/**
 * Class Almacene
 *
 * @property $id_almacen
 * @property $nombre
 * @property $direccion
 *
 * @property Estante[] $estantes
 * @property RegistrosSalida[] $registrosSalidas
 * @package App
 * @mixin \Illuminate\Database\Eloquent\Builder
 */
class Almacene extends Model
{
    protected $connection = 'inventario';
    protected $table = 'almacenes';
    /**
     * Primary key field name
     *
     * The DB uses `id_almacen` as a serial primary key, so tell Eloquent.
     */
    protected $primaryKey = 'id_almacen';
    public $timestamps = false;
    protected $perPage = 20;

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    // id_almacen is auto-generated by the DB (serial). Do not accept it in mass assignment.
    protected $fillable = ['nombre', 'direccion', 'latitud', 'longitud'];


    /**
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     */
    public function estantes()
    {
        return $this->hasMany(\Modules\Inventario\Models\Estante::class, 'id_almacen', 'id_almacen');
    }
    
    /**
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     */
    
}






