<?php

namespace Modules\Inventario\Models;

use Illuminate\Database\Eloquent\Model;

/**
 * Class Campana
 *
 * @property $id_campana
 * @property $nombre
 * @property $descripcion
 * @property $fecha_inicio
 * @property $fecha_fin
 * @property $imagen_banner
 *
 * @property Donacione[] $donaciones
 * @package App
 * @mixin \Illuminate\Database\Eloquent\Builder
 */
class Campana extends Model
{
    protected $connection = 'inventario';
    /**
     * Primary key name - DB uses id_campana as serial primary key
     */
    protected $primaryKey = 'id_campana';
    public $timestamps = false;

    protected $perPage = 20;

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    // id_campana is auto-generated by the DB. Do not mass assign it.
    protected $fillable = ['nombre', 'descripcion', 'fecha_inicio', 'fecha_fin', 'imagen_banner'];


    /**
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     */
    public function donaciones()
    {
        return $this->hasMany(\Modules\Inventario\Models\Donacione::class, 'id_campana', 'id_campana');
    }

    public function puntosRecoleccion()
    {
        return $this->hasMany(\Modules\Inventario\Models\PuntosRecoleccion::class, 'id_campana', 'id_campana');
    }
}






