<?php

namespace Modules\Inventario\Models;

use Illuminate\Database\Eloquent\Model;

/**
 * Class Espacio
 *
 * @property $id_espacio
 * @property $id_estante
 * @property $codigo_espacio
 * @property $capacidad
 * @property $unidad_medida
 *
 * @property Estante $estante
 * @property UbicacionesDonacione[] $ubicacionesDonaciones
 * @package App
 * @mixin \Illuminate\Database\Eloquent\Builder
 */
class Espacio extends Model
{
    protected $connection = 'inventario';
    /**
     * Primary key name - the DB uses id_espacio as serial primary key
     */
    protected $primaryKey = 'id_espacio';
    public $timestamps = false;

    protected $perPage = 20;

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    // id_espacio is auto-generated by the DB (serial). Do not accept it in mass assignment.
    // This model no longer stores 'capacidad' or 'unidad_medida'.
    protected $fillable = ['id_estante', 'codigo_espacio', 'estado'];


    /**
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     */
    public function estante()
    {
        return $this->belongsTo(\Modules\Inventario\Models\Estante::class, 'id_estante', 'id_estante');
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     */
    public function ubicacionesDonaciones()
    {
        return $this->hasMany(\Modules\Inventario\Models\UbicacionesDonacione::class, 'id_espacio', 'id_espacio');
    }

}






