<?php

namespace Modules\Inventario\Models;

use Illuminate\Database\Eloquent\Model;

/**
 * Class Estante
 *
 * @property $id_estante
 * @property $id_almacen
 * @property $codigo_estante
 * @property $descripcion
 *
 * @property Almacene $almacene
 * @property Espacio[] $espacios
 * @package App
 * @mixin \Illuminate\Database\Eloquent\Builder
 */
class Estante extends Model
{
    protected $connection = 'inventario';
    protected $table = 'estantes';
    /**
     * Primary key name - the DB uses id_estante as serial primary key
     */
    protected $primaryKey = 'id_estante';
    public $timestamps = false;

    protected $perPage = 20;

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    // id_estante is auto-generated by the DB (serial). Do not accept it in mass assignment.
    protected $fillable = ['id_almacen', 'codigo_estante', 'descripcion'];


    /**
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     */
    public function almacene()
    {
        return $this->belongsTo(\Modules\Inventario\Models\Almacene::class, 'id_almacen', 'id_almacen');
    }

    public function almacen()
    {
        return $this->belongsTo(\Modules\Inventario\Models\Almacene::class, 'id_almacen', 'id_almacen');
    }
    
    /**
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     */
    public function espacios()
    {
        return $this->hasMany(\Modules\Inventario\Models\Espacio::class, 'id_estante', 'id_estante');
    }
    
}






