<div class="row padding-1 p-1">
    <div class="col-md-12">

        {{-- id_producto is auto-generated by the database, do not show/edit it --}}
        <div class="form-group mb-2 mb20">
            <label for="id_categoria" class="form-label">
                {{ __('Categoria') }}
                <a href="{{ route('inventario.categorias-producto.create') }}" target="_blank" class="btn btn-xs btn-success ml-1"
                    title="Crear nueva categoría">
                    <i class="fas fa-plus"></i>
                </a>
            </label>
            <select name="id_categoria" id="id_categoria"
                class="form-control @error('id_categoria') is-invalid @enderror">
                <option value="">{{ __('-- Select --') }}</option>
                @foreach(($categorias ?? []) as $catId => $catName)
                    <option value="{{ $catId }}" {{ (string) old('id_categoria', $producto?->id_categoria) === (string) $catId ? 'selected' : '' }}>{{ $catName }}</option>
                @endforeach
            </select>
            {!! $errors->first('id_categoria', '<div class="invalid-feedback" role="alert"><strong>:message</strong></div>') !!}
        </div>
        <div class="form-group mb-2 mb20">
            <label for="nombre" class="form-label">{{ __('Nombre') }}</label>
            <input type="text" name="nombre" class="form-control @error('nombre') is-invalid @enderror"
                value="{{ old('nombre', $producto?->nombre) }}" id="nombre" placeholder="Nombre">
            {!! $errors->first('nombre', '<div class="invalid-feedback" role="alert"><strong>:message</strong></div>') !!}
        </div>
        <div class="form-group mb-2 mb20">
            <label for="descripcion" class="form-label">{{ __('Descripcion') }}</label>
            <input type="text" name="descripcion" class="form-control @error('descripcion') is-invalid @enderror"
                value="{{ old('descripcion', $producto?->descripcion) }}" id="descripcion" placeholder="Descripcion">
            {!! $errors->first('descripcion', '<div class="invalid-feedback" role="alert"><strong>:message</strong></div>') !!}
        </div>
        <div class="form-group mb-2 mb20">
            <label for="unidad_medida" class="form-label">{{ __('Unidad Medida') }}</label>
            <input type="text" name="unidad_medida" class="form-control @error('unidad_medida') is-invalid @enderror"
                value="{{ old('unidad_medida', $producto?->unidad_medida) }}" id="unidad_medida"
                placeholder="Unidad Medida">
            {!! $errors->first('unidad_medida', '<div class="invalid-feedback" role="alert"><strong>:message</strong></div>') !!}
        </div>

    </div>
    <div class="col-md-12 mt20 mt-2">
        <button type="submit" class="btn btn-primary">{{ __('Submit') }}</button>
    </div>
</div>



