<?php

namespace Modules\Inventario\Http\Requests;

use Illuminate\Foundation\Http\FormRequest;

class EspacioRequest extends FormRequest
{
    /**
     * Determine if the user is authorized to make this request.
     */
    public function authorize(): bool
    {
        return true;
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array<string, \Illuminate\Contracts\Validation\ValidationRule|array<mixed>|string>
     */
    public function rules(): array
    {
        return [
            // id_espacio is auto-generated by the DB. Validate payload fields instead.
            'id_estante' => 'required|exists:inventario.estantes,id_estante',
            'codigo_espacio' => 'nullable|string|max:255', // Auto-generated, so nullable
            // capacidad and unidad_medida were removed from the model/schema
        ];
    }
}






